- docs/source/index.mdx
- docs/source/ryzenai/overview.mdx
Update documentation following :
* https://huggingface.slack.com/archives/C05G9EZ9XAN/p1701798665373149 
* https://huggingface.slack.com/archives/C05G9EZ9XAN/p1701797067093139?thread_ts=1701578682.594879&cid=C05G9EZ9XAN
> Udpate documentation

- README.md
> Update Ryzen description

- README.md
> Add testing steps in README.md

- optimum/amd/ryzenai/configuration.py
> Fix cpu config

- optimum/amd/ryzenai/modeling.py
Fix save pretrained for pre-optimized models
> Fix save pretrained for pre-optimized models

- optimum/amd/ryzenai/modeling.py
- tests/ryzenai/test_modeling.py
- tests/ryzenai/test_quantization.py
Following updates are made
* Fix vaip_config path in tests
* Throw error when config path is wrong
> [RyzenAI] Fix vaip_config path in tests

- README.md
- docs/source/_toctree.yml
- docs/source/ryzenai/overview.mdx
- docs/source/ryzenai/package_reference/configuration.mdx
- docs/source/ryzenai/package_reference/modeling.mdx
- docs/source/ryzenai/package_reference/quantization.mdx
- docs/source/ryzenai/usage_guides/quantization.mdx
Add documentation for quantization
> [RyzenAI] Add quantization documentation

- .github/workflows/test_ryzenai_modeling.yaml
- .github/workflows/test_ryzenai_prequantized_model.yaml
- .github/workflows/test_ryzenai_quantization_timm.yaml
Run RyzenAI tests only when code changes in the `ryzenai` folders.
> Restrict RyzenAI tests

- optimum/amd/brevitas/configuration.py
Most of these configurations can be easily supported from our side, it's just a matter of assembling the pieces.
> Feat: added invalid combinations

- examples/quantization/brevitas/quantize_llm.py
Note, this also incorporates the changes in #78.
> Refactor (brevitas/example): Moved script body into a `main` function

- optimum/amd/brevitas/data_utils.py
- optimum/amd/brevitas/quantizer.py
The device wasn't set properly when we also pass KV Cache (FX quantization)
> Fix (brevitas/data): Bugfix in setting data device

- docs/source/ryzenai/overview.mdx
- docs/source/ryzenai/usage_guides/quantization.mdx
Fixes doc links and code formatting
> Fix documentation links

- README.md
- tests/ryzenai/operators_baseline.json
- tests/ryzenai/test_modeling.py
- tests/ryzenai/test_quantization.py
- tests/ryzenai/testing_utils.py
- utils/ryzenai/README.md
- utils/ryzenai/generate_operators_baseline.py
Add operator regression tests + restructure for modularity
> [RyzenAI] Add operators regression tests

- examples/quantization/brevitas/quantize_llm.py
- optimum/amd/brevitas/accelerate_utils.py
Superseeds & incorporates suggestions from #86.
> Fix (brevitas/example): Avoid offloading float model twice

- docs/Dockerfile
> Fix documentation build

- setup.py
- tests/ryzenai/operators_baseline.json
> Fix torch version

- pyproject.toml
> Update ruff params

- tests/ryzenai/operators_baseline.json
> Update Resnet baseline

- pyproject.toml
Reverts huggingface/optimum-amd#103
> Revert "Update ruff params"

- docs/Dockerfile
optimum doc build currently failing https://github.com/huggingface/optimum/actions/workflows/build_main_documentation.yml (see https://github.com/huggingface/optimum/actions/runs/8323151557)
> Fix doc building

- .github/workflows/test_ryzenai_modeling.yaml
- .github/workflows/test_ryzenai_prequantized_model.yaml
- .github/workflows/test_ryzenai_quantization_timm.yaml
- README.md
- tests/ryzenai/operators_baseline.json
- tests/ryzenai/testing_utils.py
- tests/ryzenai/vaip_config.json
> Move to Ryzen1.1

- .github/workflows/test_brevitas.yaml
- examples/quantization/brevitas/README.md
- setup.py
Fixes issues with the tests, and updates dependencies in various places. Should address the test issues in #134 & #135.
> Fix (tests/README): Update dependencies to fix tests.

- examples/quantization/brevitas/quantize_llm.py
`apply_bias_correction` argument was not passed to the quantization configuration.
> Fix: Pass on `apply_bias_correction` argument.

- docker/onnx-runtime-amd-gpu/Dockerfile
- docker/transformers-pytorch-amd-gpu-flash/Dockerfile
- docs/source/amdgpu/overview.mdx
Update doc to support MI300
Corresponding ORT Updates: https://github.com/huggingface/optimum/pull/1862
> MI300 doc updates

- .github/workflows/build_pr_documentation.yml
> Update vai_q_onnx installation
